user: my-manager-user
upassword: "secret-password"
workdir: "/home/{{ user }}/eplaypen"
logdir: "/var/log/eplaypen"

swap_file: "/swap500m"
swap_file_size: 500M

web_hostname: tryerl.seriyps.ru

pp_user: eplaypen
db_password: "secret-db-password"

# crypto:rand_bytes(16)
pastebin_key: "<<97,181,182,103,183,183,244,87,217,109,159,157,43,218,51,106>>"
cookie: "some-secret"

# features:
# - dirty_io - add +SDio 1 to minimize dirty io threads (save some resources)
# - to_dis - erlc supports `+to_dis` option
# - ssa - erlc supports `+dssa` option
# - asmdump - `erl` supports `+JDdump` flag to dump loaded modules as assembler listing
erl_releases:
  - name: 24-RC3
    tag: 24.0-rc3-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 23.3
    tag: 23.3-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 23.2
    tag: 23.2-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 23.1
    tag: 23.1-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 23.0
    tag: 23.0-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 22.3
    tag: 22.3-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 22.2
    tag: 22.2-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 22.1
    tag: 22.1.1-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 22.0
    tag: 22.0.4-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 21.3
    tag: 21.3.8.4-alpine
    features: [dirty_io, to_dis]
  - name: 20.3
    tag: 20.3.8.22-alpine
    features: [dirty_io, to_dis]
  - name: 19.3
    tag: 19.3.6.13-slim
    features: []
  - name: 18.3
    tag: 18.3.4.11-slim
    features: []
