user: my-manager-user
upassword: "secret-password"
workdir: "/home/{{ user }}/eplaypen"
logdir: "/var/log/eplaypen"

swap_file: "/swap500m"
swap_file_size: 500M

web_hostname: tryerl.seriyps.ru

pp_user: eplaypen
db_password: "secret-db-password"

# crypto:rand_bytes(16)
pastebin_key: "<<97,181,182,103,183,183,244,87,217,109,159,157,43,218,51,106>>"
cookie: "some-secret"

# features:
# - dirty_io - add +SDio 1 to minimize dirty io threads (save some resources)
# - to_dis - erlc supports `+to_dis` option
# - ssa - erlc supports `+dssa` option
# - asmdump - `erl` supports `+JDdump` flag to dump loaded modules as assembler listing
erl_releases:
  - name: 28.0
    tag: 28.0-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 27.3
    tag: 27.3-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 27.2
    tag: 27.2-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 27.1
    tag: 27.1-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 26.2
    tag: 26.2-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 26.0
    tag: 26.0-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 25.3
    tag: 25.3-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 25.2
    tag: 25.2-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 25.1
    tag: 25.1-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 25.0
    tag: 25.0-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 24.3
    tag: 24.3-alpine
    features: [dirty_io, no_dis, ssa, asmdump]
  - name: 23.3
    tag: 23.3-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 22.3
    tag: 22.3-alpine
    features: [dirty_io, to_dis, ssa]
  - name: 21.3
    tag: 21.3.8.4-alpine
    features: [dirty_io, to_dis]
  - name: 20.3
    tag: 20.3.8.22-alpine
    features: [dirty_io, to_dis]
